@file:Suppress("MagicNumber")
package br.com.brunocarvalhs.core.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF7B3FA0)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFEADCF5)
val onPrimaryContainerLight = Color(0xFF2A0A3D)
val secondaryLight = Color(0xFFB25900)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFE0B2)
val onSecondaryContainerLight = Color(0xFF3E1F00)
val tertiaryLight = Color(0xFF2E7D32)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFC8E6C9)
val onTertiaryContainerLight = Color(0xFF0F2E12)
val errorLight = Color(0xFFB3261E)
val onErrorLight = Color(0xFFFFFFFF)
val backgroundLight = Color(0xFFFAFAFA)
val onBackgroundLight = Color(0xFF1C1B1F)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF1C1B1F)
val surfaceVariantLight = Color(0xFFE7E0EC)
val onSurfaceVariantLight = Color(0xFF49454F)
val outlineLight = Color(0xFF79747E)


val primaryDark = Color(0xFFD0A9F5)
val onPrimaryDark = Color(0xFF2A0A3D)
val primaryContainerDark = Color(0xFF5B2C82)
val onPrimaryContainerDark = Color(0xFFEADCF5)
val secondaryDark = Color(0xFFFFB74D)
val onSecondaryDark = Color(0xFF3E1F00)
val secondaryContainerDark = Color(0xFF7A3E00)
val onSecondaryContainerDark = Color(0xFFFFE0B2)
val tertiaryDark = Color(0xFFA5D6A7)
val onTertiaryDark = Color(0xFF0F2E12)
val tertiaryContainerDark = Color(0xFF2E7D32)
val onTertiaryContainerDark = Color(0xFFC8E6C9)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val backgroundDark = Color(0xFF121212)
val onBackgroundDark = Color(0xFFE6E1E5)
val surfaceDark = Color(0xFF121212)
val onSurfaceDark = Color(0xFFE6E1E5)
val surfaceVariantDark = Color(0xFF49454F)
val onSurfaceVariantDark = Color(0xFFCAC4D0)
val outlineDark = Color(0xFF938F99)
