appId: br.com.brunocarvalhs.friendssecrets
name: Settings Flow
---
- launchApp
- runFlow: home_flow.yaml
- tapOn: "More options"
- tapOn: "Settings"
- assertVisible: "General"
- assertVisible: "Appearance"
- assertVisible: "Report an issue"
- assertVisible: "FAQ"
- assertVisible: "Review App"
- tapOn: "Appearance"
- assertVisible: "Appearance"
- assertVisible: "Light theme"
- assertVisible: "Dark theme"
- assertVisible: "System theme"
- assertVisible: "Dynamic Theme"
- back
- tapOn: "Report an issue"
- back
- tapOn: "FAQ"
- back
- assertVisible: "Review App"
- back
- back