name: Build Application Debug
on:
  push:
    branches: [ develop ]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  JDK_VERSION: 11
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx3072m"
  BUILD_TOOLS_VERSION: "30.0.2"
  APP_NAME: "FriendsSecrets"

jobs:
  preparing_environment:
    runs-on: ubuntu-latest
    name: Preparing Environment
    outputs:
      has-exec-permissions: ${{ steps.set_permissions.outcome == 'success' }}
      jdk-version: ${{ env.JDK_VERSION }}
      gradle-opts: ${{ env.GRADLE_OPTS }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '${{ env.JDK_VERSION }}'

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Setup Android SDK
        uses: Swisyn/setup-android-sdk@v1

      - name: Setup Gradle
        run: echo "org.gradle.daemon=false" >> $GITHUB_WORKSPACE/gradle.properties

  unit_tests:
    needs: preparing_environment
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Unit tests
        run: ./gradlew testDebug --stacktrace
        env:
          HAS_EXEC_PERMISSIONS: ${{ needs.preparing_environment.outputs.has-exec-permissions }}
          JDK_VERSION: ${{ needs.preparing_environment.outputs.jdk-version }}
          GRADLE_OPTS: ${{ needs.preparing_environment.outputs.gradle-opts }}

  android_lint:
    needs: preparing_environment
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Android Lint
        run: ./gradlew lintDebug
        env:
          HAS_EXEC_PERMISSIONS: ${{ needs.preparing_environment.outputs.has-exec-permissions }}
          JDK_VERSION: ${{ needs.preparing_environment.outputs.jdk-version }}
          GRADLE_OPTS: ${{ needs.preparing_environment.outputs.gradle-opts }}

  build:
    needs: [preparing_environment, unit_tests, android_lint]
    runs-on: ubuntu-latest
    name: Build
    env:
      KEYSTORE_ALIAS: ${{ secrets.ALIAS }}
      KEY_PASSWORD: ${{ secrets.PASSWORD_ALIAS }}
      KEYSTORE_PASSWORD: ${{ secrets.PASSWORD_KEY }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Build AAB
        run: ./gradlew bundleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.APP_NAME }}-apk
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.APP_NAME }}-aab
          path: app/build/outputs/bundle/debug/*.aab
