name: Build Application Debug

on:
  push:
    branches: [ develop ]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  JDK_VERSION: 17
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx3072m"
  BUILD_TOOLS_VERSION: "34.0.0"
  APP_NAME: "FriendsSecrets"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Application
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '${{ env.JDK_VERSION }}'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Create local.properties
        run: |
          echo "sdk.dir=${{ env.ANDROID_HOME }}" > local.properties
          echo "apiKey=${{ secrets.API_KEY }}" >> local.properties
          
      - name: Get Gradle Version from gradle.properties
        id: gradle-version
        run: |
          GRADLE_VERSION=$(grep "gradleVersion" gradle.properties | cut -d'=' -f2 | tr -d ' ')
          echo "gradle_version=${GRADLE_VERSION}" >> $GITHUB_ENV
          echo "Gradle version is $GRADLE_VERSION"
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ env.gradle_version }}

      - name: Create google-services release file
        run: |
          rm -f app/google-services.json
          echo ${{ secrets.GOOGLE_SERVICE_JSON }} | base64 --decode > app/google-services.json

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Run Unit Tests
        run: ./gradlew testDebug
        env:
          GRADLE_OPTS: ${{ env.GRADLE_OPTS }}

      - name: Check for Unit Test Failures
        if: ${{ failure() }}
        run: exit 1
      
      - name: Run Lint
        run: ./gradlew lintDebug
        env:
          GRADLE_OPTS: ${{ env.GRADLE_OPTS }}

      - name: Check for Lint Failures
        if: ${{ failure() }}
        run: exit 1

      - name: Build and Sign APK Debug
        run: |
          ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.APP_NAME }}-apk-debug
          path: app/build/outputs/apk/debug/*.apk

      - name: Build AAB
        run: |
          ./gradlew bundleDebug

      - name: Upload Debug AAB
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.APP_NAME }}-aab-debug
          path: app/build/outputs/bundle/debug/*.aab
