name: Build and Release Application

on:
  push:
    branches: [ master ]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  JDK_VERSION: 17
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx3072m"
  BUILD_TOOLS_VERSION: "34.0.0"
  APP_NAME: "FriendsSecrets"

jobs:
  checkout-and-setup:
    runs-on: ubuntu-24.04
    name: Checkout and Setup Environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '${{ env.JDK_VERSION }}'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Create local.properties
        run: |
          echo "sdk.dir=${{ env.ANDROID_HOME }}" > local.properties
          echo "apiKey=${{ secrets.API_KEY }}" >> local.properties
      
      - name: Create google-services.json
        run: |
          echo ${{ secrets.GOOGLE_SERVICE_JSON }} | base64 --decode > app/google-services.json

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Upload Workspace
        uses: actions/upload-artifact@v3
        with:
          name: workspace
          path: ./

  unit-tests:
    runs-on: ubuntu-24.04
    name: Unit Tests
    needs: checkout-and-setup
    steps:
      - name: Download Workspace
        uses: actions/download-artifact@v3
        with:
          name: workspace

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Run Unit Tests
        run: ./gradlew testDebug
        env:
          GRADLE_OPTS: ${{ env.GRADLE_OPTS }}

  lint-check:
    runs-on: ubuntu-24.04
    name: Lint Check
    needs: checkout-and-setup
    steps:
      - name: Download Workspace
        uses: actions/download-artifact@v3
        with:
          name: workspace

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Run Lint
        run: ./gradlew lintDebug
        env:
          GRADLE_OPTS: ${{ env.GRADLE_OPTS }}

  build-apk:
    runs-on: ubuntu-24.04
    name: Build APK
    needs: [unit-tests, lint-check]
    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
    steps:
      - name: Download Workspace
        uses: actions/download-artifact@v3
        with:
          name: workspace

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Generate Keystore
        run: |
          echo ${{ secrets.RELEASE_KEYSTORE }} | base64 --decode > app/release.keystore

      - name: Check if keystore exists
        run: |
          if [ -f "app/release.keystore" ]; then
            echo "Keystore exists"
          else
            echo "::error::Keystore file 'app/release.keystore' does not exist. Please ensure it is in the correct location."
            exit 1
          fi
        
      - name: Build APK
        run: ./gradlew assembleRelease
            
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.APP_NAME }}-apk
          path: app/build/outputs/apk/release/*.apk

  build-aab:
    runs-on: ubuntu-24.04
    name: Build AAB
    needs: [unit-tests, lint-check]
    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
    steps:
      - name: Download Workspace
        uses: actions/download-artifact@v3
        with:
          name: workspace

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Generate Keystore
        run: |
          echo ${{ secrets.RELEASE_KEYSTORE }} | base64 --decode > app/release.keystore

      - name: Check if keystore exists
        run: |
          if [ -f "app/release.keystore" ]; then
            echo "Keystore exists"
          else
            echo "::error::Keystore file 'app/release.keystore' does not exist. Please ensure it is in the correct location."
            exit 1
          fi

      - name: Build AAB
        run: ./gradlew bundleRelease
            
      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.APP_NAME }}-aab
          path: app/build/outputs/bundle/release/*.aab

  release:
    runs-on: ubuntu-24.04
    name: Create and Upload Release
    needs: [build-apk, build-aab]
    steps:
      - name: Get App Version
        run: echo "version=$(cat VERSION.md)" >> $GITHUB_ENV

      - name: Calculate module name
        id: module_name
        run: |
          MODULE_NAME=$(echo "${{ github.repository }}" | awk -F'/' '{print $2}')
          echo "module_name=$MODULE_NAME" >> $GITHUB_ENV

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.version }}
          release_name: ${{ env.module_name }} v${{ env.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Upload Release APK
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: app/build/outputs/apk/release/*.apk
          asset_name: ${{ env.module_name }}-apk-release.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Release AAB
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: app/build/outputs/bundle/release/*.aab
          asset_name: ${{ env.module_name }}-release.aab
          asset_content_type: application/octet-stream
