name: Android Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  checkout-and-setup:
    runs-on: ubuntu-24.04
    name: Checkout and Setup Environment
    outputs:
      jdk_version: ${{ steps.config.outputs.jdk_version }}
      gradle_opts: ${{ steps.config.outputs.gradle_opts }}
      app_name: ${{ steps.config.outputs.app_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load Pipeline Configuration
        id: config
        run: |
          echo "jdk_version=$(yq '.project.jdk_version' .github/pipeline-config.yaml)" >> $GITHUB_OUTPUT
          echo "gradle_opts=$(yq '.project.gradle_opts' .github/pipeline-config.yaml)" >> $GITHUB_OUTPUT
          echo "app_name=$(yq '.project.name' .github/pipeline-config.yaml)" >> $GITHUB_OUTPUT

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ steps.config.outputs.jdk_version }}

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Create local.properties
        run: |
          echo "sdk.dir=${{ env.ANDROID_HOME }}" > local.properties

      - name: Create google-services.json
        run: |
          echo ${{ secrets.GOOGLE_SERVICE_JSON }} | base64 --decode > app/google-services.json

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Upload Workspace
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: ./
          
  unit-tests:
    runs-on: ubuntu-24.04
    name: Run Unit Tests
    needs: checkout-and-setup
    steps:
      - name: Download Workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Run Unit Tests
        run: $(yq '.stages.unit_tests.command' .github/pipeline-config.yaml)
        env:
          GRADLE_OPTS: ${{ needs.checkout-and-setup.outputs.gradle_opts }}

      - name: Comment Failure
        if: ${{ failure() }}
        uses: mb2dev/github-action-comment-pull-request@1.0.0
        with:
          message: "❌ Ops, encontrado falhas nos testes unitários, por favor corrija."
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          reactions: "-1 | confused"

      - name: Comment Success
        if: ${{ success() }}
        uses: mb2dev/github-action-comment-pull-request@1.0.0
        with:
          message: "✅ Todos os testes unitários passaram com sucesso! Bom trabalho."
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          reactions: "+1"


  lint-check:
    runs-on: ubuntu-24.04
    name: Run Lint Check
    needs: checkout-and-setup
    steps:
      - name: Download Workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Run Lint
        run: $(yq '.stages.lint.command' .github/pipeline-config.yaml)
        env:
          GRADLE_OPTS: ${{ needs.checkout-and-setup.outputs.gradle_opts }}

      - name: Comment Failure
        if: ${{ failure() }}
        uses: mb2dev/github-action-comment-pull-request@1.0.0
        with:
          message: "❌ Ops, encontrado falhas no lint, por favor corrija."
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          reactions: "-1 | confused"

      - name: Comment Success
        if: ${{ success() }}
        uses: mb2dev/github-action-comment-pull-request@1.0.0
        with:
          message: "✅ Todos os lints passaram com sucesso! Bom trabalho."
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          reactions: "+1"

  detekt-check:
    runs-on: ubuntu-24.04
    name: Run Detekt Check
    needs: checkout-and-setup
    steps:
      - name: Download Workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Run Detekt
        run: $(yq '.stages.detekt.command' .github/pipeline-config.yaml)
        env:
          GRADLE_OPTS: ${{ needs.checkout-and-setup.outputs.gradle_opts }}

      - name: Comment Failure
        if: ${{ failure() }}
        uses: mb2dev/github-action-comment-pull-request@1.0.0
        with:
          message: "❌ Ops, encontrado falhas no detekt, por favor corrija."
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          reactions: "-1 | confused"

      - name: Comment Success
        if: ${{ success() }}
        uses: mb2dev/github-action-comment-pull-request@1.0.0
        with:
          message: "✅ Todos os detekts passaram com sucesso! Bom trabalho."
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          reactions: "+1"

  build:
    runs-on: ubuntu-24.04
    name: Build
    needs: [checkout-and-setup, unit-tests, lint-check, detekt-check]
    steps:
      - name: Download Workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Build APK Debug
        run: $(yq '.stages.build.command' .github/pipeline-config.yaml)

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.checkout-and-setup.outputs.app_name }}-apk-debug
          path: app/build/outputs/apk/debug/*.apk
